version: '3.8'

services:
  database-mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - web-server-network

  web-server-nodejs:
    image: sc22kr/web-server-image:latest
    container_name: web-server-nodejs-container
    restart: always
    depends_on:
      - database-mongodb
    ports:
      - "3001:3001"
    networks:
      - web-server-network

networks:
  web-server-network:
    driver: bridge